services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: nusawisata-web
        depends_on:
            - database
        ports:
            - "3002:80"
        # volumes:
        #     - frontend:/var/www
    # nginx:
    #     image: nginx:stable-alpine
    #     container_name: nusawisata-nginx
    #     ports:
    #         - "8080:80"
    #     volumes:
    #         - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    #         - frontend:/var/www
    #     depends_on:
    #         - web
    database:
        image: mysql:8.0.41-debian
        container_name: nusawisata-database
        ports:
            - "43306:3306"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: true
        volumes:
            - dbdata:/var/lib/mysql
volumes:
    dbdata:
    # frontend:
